### ISSUE TITLE
combine-prs should not combine PRs targeting different branches

### ISSUE THREAD

**Issue by benCoomes** [github/combine-prs#11]
When PRs exist on multiple branches, combine-pr should not attempt to combine them into the same PR. 

For example, if I have:
* PR1 (`main` <- `patch-main-1`)
* PR2 (`main` <- `patch-main-2`)
* PR3 (`release-2.3` <- `patch-release-1`)
* PR4 (`release-2.3` <- `patch-release-2`)

Then `combine-prs` will put all 4 PRs into the same branch. I'm not 100% sure how the target branch is choosen - whatever the last PR in the group targets?

Ideally, `combine-prs` would either create a PR for each target branch, or be configurable to operate on PRs targeting a single branch (configurable, defaulting to the default branch). 
  
The challenge with creating multiple PRs is that the action would need to create branches with different names (and maybe different PR titles, too). It's not clear what to do if the user provides a branch name to use, since they might be depending on that exact branch name elsewhere.

So perhaps operating on a single configurable target branch is the best option.

**Comment by GrantBirki** [comment]
resolved by https://github.com/github/combine-prs/pull/14
