### ISSUE TITLE
Feature: Filter Dependabot PRs based on a minimum package age

### ISSUE THREAD

**Issue by diogoteles08** [github/combine-prs#47]
Currently Dependabot has an open issue with this same purpose (https://github.com/dependabot/dependabot-core/issues/3651), and it would be really useful if combine-prs could provide a provisory solution for this. It would be a very relevant change concerning security, as well explained on [this comment](https://github.com/dependabot/dependabot-core/issues/3651#issuecomment-1326124683).

Renovate bot already has a similar feature and they call it [stabilityDays](https://docs.renovatebot.com/configuration-options/#stabilitydays).

**Comment by GrantBirki** [comment]
@diogoteles08 I love this idea! However, I don't think this Action is the correct place to solve this particular issue. This Action pretty much just combines a bunch of branches (typically dependabot) into a [single branch](https://github.com/github/combine-prs/blob/a1b441298ab012db2ae25f7bf5fad0b7f78db9c4/src/main.js#L129-L146). It doesn't have any code or plans to reach out check and see how many days a dependency has been released for or how long the original dependency PR was opened for.

I think that the https://github.com/dependabot/dependabot-core/issues/3651 issue is the correct place for this problem to be solved and I think it would bring a lot of value to the open source community as well!

PS its so awesome to see that you are working on securing open source software with GOOST! 🎉 👻
